### ISSUE TITLE
The sounds from the bell interrupt the soundtrack

### ISSUE THREAD

**Issue by WeltieKit** [Hibiii/Windchimes#5]
The music of the game is cut off when the bell sounds.

**Comment by Hibiii** [comment]
How so? I've tested with jukeboxes and the game's own soundtrack and I couldn't reproduce. Could you go into more detail?

**Comment by WeltieKit** [comment]
For no reason, the problem resolved itself. It is not cut now, but I took a video of it. It looks good for now.
